import Head from "next/head";
import Banner from "../components/Banner";
import Header from "../components/Headers";
import ProductFeeds from "../components/Products";
import type { Products } from "../types/typings";

const Home = ({ products }: Products) => {
  return (
    <>
      <Head>
        <title>Amazon 2.0</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="mx-auto max-w-screen-2xl bg-gray-100">
        <Banner />

        <ProductFeeds products={products} />
      </main>
    </>
  );
};

export default Home;

export async function getServerSideProps(ctx: any) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );

  return {
    props: {
      products,
    },
  };
}
